[workspace]
resolver = '2'
# members = ["programs/*", "client"]
members = ["programs/*"]

[profile.test]
opt-level = 0


[profile.release]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false
rpath = false
lto = true
overflow-checks = true
panic = 'abort'
